
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Image image4;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry txt_url;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HScale hs_speed;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Entry txt_cookie;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry txt_captcha;
	
	private global::Gtk.CheckButton chk_license;
	
	private global::Gtk.Button btn_startstop;
	
	private global::Gtk.Label lbl_count;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Test their database, poi!");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(3));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image ();
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("KanColleJ.Bt3vyaX.jpg");
		this.hbox3.Add (this.image4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image4]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("登录页面");
		this.hbox5.Add (this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.txt_url = new global::Gtk.Entry ();
		this.txt_url.CanFocus = true;
		this.txt_url.Name = "txt_url";
		this.txt_url.Text = global::Mono.Unix.Catalog.GetString ("http://gc.moejn.cn/login.html");
		this.txt_url.IsEditable = true;
		this.txt_url.InvisibleChar = '●';
		this.hbox5.Add (this.txt_url);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txt_url]));
		w3.Position = 1;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("提交速度");
		this.hbox6.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hs_speed = new global::Gtk.HScale (null);
		this.hs_speed.CanFocus = true;
		this.hs_speed.Name = "hs_speed";
		this.hs_speed.Adjustment.Lower = 1;
		this.hs_speed.Adjustment.Upper = 100;
		this.hs_speed.Adjustment.PageIncrement = 10;
		this.hs_speed.Adjustment.StepIncrement = 1;
		this.hs_speed.Adjustment.Value = 10;
		this.hs_speed.DrawValue = true;
		this.hs_speed.Digits = 0;
		this.hs_speed.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox6.Add (this.hs_speed);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hs_speed]));
		w6.Position = 1;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString (" Cookies ");
		this.hbox7.Add (this.label4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label4]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.txt_cookie = new global::Gtk.Entry ();
		this.txt_cookie.CanFocus = true;
		this.txt_cookie.Name = "txt_cookie";
		this.txt_cookie.IsEditable = true;
		this.txt_cookie.InvisibleChar = '●';
		this.hbox7.Add (this.txt_cookie);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.txt_cookie]));
		w9.Position = 1;
		this.vbox2.Add (this.hbox7);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString (" 验 证 码 ");
		this.hbox4.Add (this.label5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label5]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txt_captcha = new global::Gtk.Entry ();
		this.txt_captcha.CanFocus = true;
		this.txt_captcha.Name = "txt_captcha";
		this.txt_captcha.IsEditable = true;
		this.txt_captcha.InvisibleChar = '●';
		this.hbox4.Add (this.txt_captcha);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txt_captcha]));
		w12.Position = 1;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.chk_license = new global::Gtk.CheckButton ();
		this.chk_license.CanFocus = true;
		this.chk_license.Name = "chk_license";
		this.chk_license.Label = global::Mono.Unix.Catalog.GetString ("我同意我仅将本软件用于实验用途，作者不承担任何由于直接或间接造成的危害的法律责任");
		this.chk_license.DrawIndicator = true;
		this.chk_license.UseUnderline = true;
		this.vbox2.Add (this.chk_license);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.chk_license]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.btn_startstop = new global::Gtk.Button ();
		this.btn_startstop.Sensitive = false;
		this.btn_startstop.CanFocus = true;
		this.btn_startstop.Name = "btn_startstop";
		this.btn_startstop.UseUnderline = true;
		this.btn_startstop.Label = global::Mono.Unix.Catalog.GetString ("开始(_S)");
		this.vbox2.Add (this.btn_startstop);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btn_startstop]));
		w15.Position = 5;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lbl_count = new global::Gtk.Label ();
		this.lbl_count.Name = "lbl_count";
		this.lbl_count.LabelProp = global::Mono.Unix.Catalog.GetString ("已发送： 0 次");
		this.vbox2.Add (this.lbl_count);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lbl_count]));
		w16.Position = 6;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox3.Add (this.vbox2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox2]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.hbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 673;
		this.DefaultHeight = 486;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.chk_license.Clicked += new global::System.EventHandler (this.licensecheck);
		this.btn_startstop.Clicked += new global::System.EventHandler (this.startstopatk);
	}
}
